In [4]:
import numpy as np

In [6]:
a= np.array([1,2,3,4,5]) # creat an array
a

array([1, 2, 3, 4, 5])

In [7]:
a.ndim # checking the dimension

1

In [11]:
a=np.array([[1,2,3,4,5],[2,9,8,7,5]])
a

array([[1, 2, 3, 4, 5],
       [2, 9, 8, 7, 5]])

In [12]:
a.ndim

2

In [17]:
a=np.array([[[2,4,6,8,9],[12,56,89,32,19],[29,17,18,96,35]]])
a

array([[[ 2,  4,  6,  8,  9],
        [12, 56, 89, 32, 19],
        [29, 17, 18, 96, 35]]])

In [18]:
a.ndim

3

# *ZEROS ND ONES*

In [22]:
var1=np.zeros(10)
var1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
var2=np.ones(10)
var2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [25]:
np.zeros([2,9,1])

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

# *ARRAY*

In [26]:
var=np.array([29,91,76,81,69])
var

array([29, 91, 76, 81, 69])

In [27]:
type(var)

numpy.ndarray

In [28]:
var.argmax()

1

In [29]:
var.argmin()

0

In [30]:
var[3]


81

In [31]:
var[0:2]

array([29, 91])

In [32]:
var

array([29, 91, 76, 81, 69])

In [33]:
var[1:3]

array([91, 76])

In [34]:
var[0:4]

array([29, 91, 76, 81])

In [35]:
var[0:-1]

array([29, 91, 76, 81])

In [36]:
var[-2:2]

array([], dtype=int32)

In [38]:
arr1=np.array([2,7,90,6.8,3]) # creata a numpy array with size 5 and datatype of float
arr1

array([ 2. ,  7. , 90. ,  6.8,  3. ])

In [39]:
arr1.size

5

In [41]:
arr1.dtype

dtype('float64')

In [ ]:
# creat a two dim array
# four array in the external array
#it should have two elements each

In [44]:
arr2=np.array([[2,9],[7,1],[6,8],[3,4]])
arr2

array([[2, 9],
       [7, 1],
       [6, 8],
       [3, 4]])

In [45]:
arr2.size

8

In [46]:
arr2.ndim

2

# *RESIZE ND RESHSAPE*

In [50]:
arr3=np.arange(11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr3.ndim

1

In [55]:
arr4=np.arange(15).reshape(5,3)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [56]:
arr4.ndim

2

In [57]:
arr4.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [58]:
arr4.shape

(5, 3)

In [60]:
arr4.max()

14

In [61]:
arr4.min()

0

In [62]:
np.sqrt(arr4)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739]])

In [65]:
np.log(arr4)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_7944\3773399196.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr4)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733]])

# *TRANSPOSE*

In [66]:
s=arr4.reshape(3,5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
q=s.T
q

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#  *FLOAR ND CEIL*

In [71]:
arr5=np.array([2.9,76.19,8.5,9.4,10.55,36.3,1.69])
arr5

array([ 2.9 , 76.19,  8.5 ,  9.4 , 10.55, 36.3 ,  1.69])

In [72]:
np.floor(arr5)

array([ 2., 76.,  8.,  9., 10., 36.,  1.])

In [73]:
np.ceil(arr5)

array([ 3., 77.,  9., 10., 11., 37.,  2.])

In [75]:
arr6=np.round(arr5)
arr6

array([ 3., 76.,  8.,  9., 11., 36.,  2.])

# *STACKING*

In [80]:
arr7=np.arange(10).reshape(2,5)
arr8=np.arange(20).reshape(4,5)
arr7

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
np.vstack((arr7,arr8)) # vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
arr7=np.arange(10).reshape(5,2)   # horizondal stack
arr8=np.arange(20).reshape(5,4)
arr7

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [88]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [89]:
np.hstack((arr7,arr8))

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

In [ ]:
# for vertical stack the number of column should be equal
# for horizondal stack the number of row should be equal

# *Numpy SLIT*

In [91]:
arr9=np.arange(100).reshape(10,10)
arr9

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
np.vsplit(arr9,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [95]:
np.vsplit(arr9,10)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]]),
 array([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]),
 array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [96]:
# create a array shape 20,10 and divide it into 2 equal parts horizondaliy

In [97]:
arr10=np.arange(200).reshape(20,10)
arr10

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [98]:
np.hsplit(arr10,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,